### ISSUE TITLE
Can't connect to a local postgres DB from SQL notebook

### ISSUE THREAD

**Issue by ltoeroek** [twosigma/beakerx#7525]
java.sql.SQLException: Cannot create PoolableConnectionFactory ([Amazon][JDBC](10100) Connection Refused: [Amazon][JDBC](11640) Required Connection Key(s): PWD, UID; [Amazon][JDBC](11480) Optional Connection Key(s): AccessKeyID, AuthMech, AutoCreate, BlockingRowsMode, ClusterID, DbGroups, DisableIsValidQuery, DriverLogLevel, EndpointUrl, FilterLevel, IAMDuration, Language, loginTimeout, OpenSourceSubProtocolOverride, plugin_name, profile, Region, SecretAccessKey, SessionToken, socketTimeout, ssl, sslcert, sslfactory, sslkey, sslpassword, sslrootcert, SSLTruststore , SSLTrustStorePath, tcpKeepAlive, TCPKeepAliveMinutes, unknownLength)

Reproduce:
1. Open a new SQL notebook
2. Add the following two lines:
%defaultDatasource jdbc:postgresql://localhost:5432/mydb
SELECT 1;

**Comment by scottdraves** [comment]
thanks for the report, will look into it.

**Comment by psychemedia** [comment]
I'm getting this same error using `beakerx/beakerx` Docker container connected via Docker compose to a postgres container:

```
version: "3"
services:

  beakerx:
    image: beakerx/beakerx
    ports:
      - "8895:8888"
    links:
      - postgres
    volumes:
          - "./notebooks:/notebooks"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
```

`%defaultDatasource jdbc:postgresql://test:test@postgres/test`

gives::

```
java.sql.SQLException: Cannot create PoolableConnectionFactory ([Amazon][JDBC](10100) Connection Refused: [Amazon][JDBC](11640) Required Connection Key(s): PWD, UID; [Amazon][JDBC](11480) Optional Connection Key(s): AccessKeyID, AuthMech, AutoCreate, BlockingRowsMode, ClusterID, DbGroups, DisableIsValidQuery, DriverLogLevel, EndpointUrl, FilterLevel, IAMDuration, Language, loginTimeout, OpenSourceSubProtocolOverride, plugin_name, profile, Region, SecretAccessKey, SessionToken, socketTimeout, ssl, sslcert, sslfactory, sslkey, sslpassword, sslrootcert, SSLTruststore , SSLTrustStorePath, tcpKeepAlive, TCPKeepAliveMinutes, unknownLength)
```
